version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ndlKuberCul57#dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080